### ISSUE TITLE
there is something wrong with degraded_img use your algorithmn , i dont kown why?

### ISSUE THREAD

**Issue by erjihaoshi** [vvictoryuki/BSRGAN_implementation#2]
![00017](https://user-images.githubusercontent.com/37402962/116393822-b443e600-a854-11eb-9a52-de91c3d2599a.png)

**Comment by mychina75** [comment]
Hi, there. 
How did you solve the issue? thanks.

**Comment by brstar96** [comment]
> Hi, there.
> How did you solve the issue? thanks.

https://github.com/cszn/BSRGAN/issues/7
Check this out!
