### ISSUE TITLE
Color distortion and ValueError

### ISSUE THREAD

**Issue by IceClear** [vvictoryuki/BSRGAN_implementation#5]
Hi, @vvictoryuki, nice work! But during the test, I found there seems to be some errors:

- `Traceback (most recent call last):
  File "degrade.py", line 313, in <module>
    restore_img = degradation_pipeline(img)
  File "degrade.py", line 143, in degradation_pipeline
    img = get_camera(img, degrade_dict)
  File "degrade.py", line 223, in get_camera
    deg_img = np.array(deg_img).astype(np.uint8)
ValueError: setting an array element with a sequence.`
I wonder if this should be fixed by changing https://github.com/vvictoryuki/BSRGAN_implementation/blob/main/degrade.py#L223 to be:
 `with tf.Session() as sess:  deg_img = deg_img.eval(session=sess)`
to transfer a tensor to numpy array.

- Furthermore, I found it strange that there will be color distortion if you first downsample the image using cv2.resize() then add camera noise using get_camera(). Like this: 
![图片](https://user-images.githubusercontent.com/22350795/118761919-db1b9800-b8a7-11eb-8606-241e87cd5292.png). I wonder if this is a bug or a common phenomenon. Have you noticed such a case? How to fix it? Thanks.

**Comment by yujiwen** [comment]
I'm glad to see your question. As for camera sensor noise, my implementation method is largely based on the open source code of this [work.](https://github.com/timothybrooks/unprocessing#unprocessing-images-for-learned-raw-denoising) I'm not very familiar with tensorflow, so I just made a little modification. I noticed that the camera sensor noise processing in the original bsrgan is actually more complex than the work I refer to, so I can't guarantee that this part of the code is a complete reproduction of the method proposed by the author of bsrgan. As for the color distortion problem you mentioned, the main problem I encountered was the distortion of image brightness or contrast. I tried to use tone mapping to correct it, but the effect was limited. However, the experimental results I have given are all done without camera sensor noise. In fact, the effect is very good. I have also tried to add camera sensor noise, but there seems to be no gain in visual effect. I personally prefer that camera sensor noise may not be so important when other degradation parameters are complex enough. Hope to help you!

**Comment by IceClear** [comment]
Thanks for your patient reply. Yes, you really realize a good performance! Actually, I just want to figure out the color distortion phenomenon I referred to, since I also rebuilt the data process code in BSRGAN and this is the only problem I encounted without solutions. Anyway, thanks for your answers :)
